version: '3.8'
services:
  leconfe:
    image: leconfe:latest
    container_name: leconfe_app
    restart: unless-stopped
    ports:
      - "8086:8080"
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime
      - ./.env:/var/www/html/.env
      - leconfe_storage:/var/www/html/storage
      - leconfe_public:/var/www/html/public
    networks:
      - leconfe_net

volumes:
  leconfe_storage:
  leconfe_public:

networks:
  leconfe_net:
    driver: bridge
